# Generated by Django 3.2.6 on 2024-02-03 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quetions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('duraction_time', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='home.category')),
                ('is_edit', models.ManyToManyField(related_name='edit_sers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quetions_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('a', models.CharField(max_length=400)),
                ('b', models.CharField(max_length=400)),
                ('d', models.CharField(max_length=400)),
                ('c', models.CharField(max_length=400)),
                ('true_ansver', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('d', 'd'), ('c', 'c')], max_length=40)),
                ('quetions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quetions_list', to='home.quetions')),
            ],
        ),
    ]
