# Generated by Django 3.2.6 on 2024-02-15 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
                ('duraction_time', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
                ('is_score', models.IntegerField(default=0)),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_category', to='quiz.category')),
                ('is_edit', models.ManyToManyField(blank=True, related_name='edit_sers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('using_users', models.ManyToManyField(blank=True, related_name='using_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true', models.IntegerField(default=0)),
                ('false', models.IntegerField(default=0)),
                ('using_count', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=400)),
                ('dates2', models.DateField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='quiz.quetions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quetions_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('a', models.CharField(max_length=400)),
                ('b', models.CharField(max_length=400)),
                ('d', models.CharField(max_length=400)),
                ('c', models.CharField(max_length=400)),
                ('true_ansver', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('d', 'd'), ('c', 'c')], max_length=40)),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
                ('quetions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quetions_list', to='quiz.quetions')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
