# Generated by Django 3.2.6 on 2024-02-03 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetions',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='quetions_list',
            name='true_ansver',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('d', 'd'), ('c', 'c')], max_length=40),
        ),
    ]
