# Generated by Django 3.2.6 on 2024-02-05 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20240203_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetions_list',
            name='random_url',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
