# Generated by Django 3.2.6 on 2024-02-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='score',
            new_name='false',
        ),
        migrations.AddField(
            model_name='result',
            name='true',
            field=models.IntegerField(default=0),
        ),
    ]
