# Generated by Django 3.2.6 on 2024-02-11 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20240205_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='quetions',
            name='using_users',
            field=models.ManyToManyField(blank=True, related_name='using_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quetions',
            name='is_edit',
            field=models.ManyToManyField(blank=True, related_name='edit_sers', to=settings.AUTH_USER_MODEL),
        ),
    ]
